# Generated by Django 4.2.17 on 2024-12-19 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='', upload_to='')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField()),
                ('Added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Tag_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
                ('Tag_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Author_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.author')),
                ('Book_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Authors',
            field=models.ManyToManyField(through='bookshelf.Book_Author_Link', to='bookshelf.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='Tags',
            field=models.ManyToManyField(through='bookshelf.Book_Tag_Link', to='bookshelf.tag'),
        ),
    ]
