# Generated by Django 4.2.17 on 2024-12-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
