# Generated by Django 4.2.17 on 2024-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_rename_authors_author_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Authors',
            field=models.ManyToManyField(through='bookshelf.Book_Author_Link', to='bookshelf.author'),
        ),
    ]
