# Generated by Django 4.2.17 on 2024-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_book_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Tags',
            field=models.ManyToManyField(through='bookshelf.Book_Tag_Link', to='bookshelf.tag'),
        ),
    ]
